/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false ../vote-collector/src/worker-env.d.ts` (hash: 034bd19ce97285c6448e2190cc2eebe9)
interface __BaseEnv_Env {
	DB: D1Database;
	DAPP_DEFINITION_ADDRESS: "account_tdx_2_12x50w93rgzgyzxek5y4ku24aa5nn9k0jqzlv5gg7jycwe9jzs26ang" | "account_rdx128y905cfjwhah5nm8mpx5jnlkshmlamfdd92qnqpy6pgk428qlqxcf";
	DEX_POSITION_CONCURRENCY: "1";
	ENV: "preview" | "production";
	GOVERNANCE_COMPONENT_ADDRESS: "component_tdx_2_1cz39h4p559znxv9vxm6vyaxwyewwdyjl0qyswwssw524euat7vjyu4" | "component_rdx1cz8tzcyyj9zlactrq9nqcnnagg56fn84p4e73gvlzp2s6krde89k9y";
	NETWORK_ID: "2" | "1";
	POLL_RUN_DURATION: "25 seconds";
	POLL_TIMEOUT_DURATION: "60 seconds";
	VOTE_CALCULATION_CONCURRENCY: "1";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../../consultation/src/server");
	}
	interface PreviewEnv {
		DB: D1Database;
		DAPP_DEFINITION_ADDRESS: "account_tdx_2_12x50w93rgzgyzxek5y4ku24aa5nn9k0jqzlv5gg7jycwe9jzs26ang";
		DEX_POSITION_CONCURRENCY: "1";
		ENV: "preview";
		GOVERNANCE_COMPONENT_ADDRESS: "component_tdx_2_1cz39h4p559znxv9vxm6vyaxwyewwdyjl0qyswwssw524euat7vjyu4";
		NETWORK_ID: "2";
		POLL_RUN_DURATION: "25 seconds";
		POLL_TIMEOUT_DURATION: "60 seconds";
		VOTE_CALCULATION_CONCURRENCY: "1";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DAPP_DEFINITION_ADDRESS" | "DEX_POSITION_CONCURRENCY" | "ENV" | "GOVERNANCE_COMPONENT_ADDRESS" | "NETWORK_ID" | "POLL_RUN_DURATION" | "POLL_TIMEOUT_DURATION" | "VOTE_CALCULATION_CONCURRENCY">> {}
}
